### ISSUE TITLE
argument error

### ISSUE THREAD

**Issue by rz-1** [CameronDeweerd/FFXIV-Market-Calculator#11]
running for the first time and received this error.

```
E:\git\FFXIV-Market-Calculator>python main.py
Got raw datacentre CSV
got raw world CSV
datacentres CSV filtered to only usable
worlds CSV filtered to only usable
[('key', '0', '1'), ('marketboard_type', 'location', 'last_id'), ('STRING', 'STRING NOT NULL UNIQUE', 'INTEGER'), ('World', 'Zurvan', '0')]
base state table data
datacentre table created
world table created
New Global DB Created
Got marketable ID list
Got raw item CSV
Got raw recipe CSV
item CSV filtered to only marketable
recipes CSV filtered to only marketable
item table created
Error: 'Incorrect number of bindings supplied. The current statement uses 47, and there are 49 supplied.'
Many Query: INSERT INTO recipe VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
recipe table created
Sales Data Added to Database
Traceback (most recent call last):
  File "E:\git\FFXIV-Market-Calculator\main.py", line 457, in <module>
    main()
  File "E:\git\FFXIV-Market-Calculator\main.py", line 436, in main
    update(location_db, location, start_id, update_quantity)
  File "E:\git\FFXIV-Market-Calculator\main.py", line 277, in update
    update_ingredient_costs(location_db)
  File "E:\git\FFXIV-Market-Calculator\main.py", line 235, in update_ingredient_costs
    location_db.execute_query_many(
  File "E:\git\FFXIV-Market-Calculator\sql_helpers.py", line 82, in execute_query_many
    cursor.executemany(query)
TypeError: executemany expected 2 arguments, got 1
```

**Comment by XxInvictus** [comment]
Is this the version pulled from this Repo or from my fork? I am just trying to ascertain if this error was before or after my changes which haven't been merged in yet trimming down the column count.

I have tried to delete both databases on my working version which is my fork and confirmed it created both databases and all tables without error.

If you can try using my fork, https://github.com/XxInvictus/FFXIV-Market-Calculator

If that doesn't work check your Python version, I am running 3.10, and can you please provide your config file, you didn't really give anything for me to replicate with the exact settings used.

**Comment by rz-1** [comment]
@XxInvictus thanks for the help. Just getting back to this and your PR on the main branch is working for me now. Cheers
